<?xml version="1.0"?>
<package format="3">
  <name>puzzle_coordinator_node</name>
  <version>0.1.0</version>
  <description>Closed-loop scan, placement request, and visual verification coordinator.</description>
  <maintainer email="monthwu@example.com">MonthWU</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>vision_interfaces</depend>

  <export><build_type>ament_cmake</build_type></export>
</package>
